<<<<<<< HEAD
# Generated by Django 5.2.5 on 2025-08-13 18:49
=======
# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 11:00
from __future__ import unicode_literals
>>>>>>> 840a6ab953452f08603e5f79b0fdbb2fa9ade5bd

from django.db import migrations, models


class Migration(migrations.Migration):
<<<<<<< HEAD

=======
>>>>>>> 840a6ab953452f08603e5f79b0fdbb2fa9ade5bd
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
<<<<<<< HEAD
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('phn_no', models.CharField(max_length=15, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dname', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('phn_no', models.CharField(unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('e_id', models.IntegerField(unique=True)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('sal', models.CharField(max_length=20)),
                ('phn_no', models.CharField(max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('m_id', models.IntegerField(unique=True)),
                ('mname', models.CharField(max_length=30)),
                ('dname', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=30)),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pname', models.CharField(max_length=30)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('phn_no', models.CharField(max_length=15, unique=True)),
                ('price', models.BigIntegerField()),
                ('qty', models.BigIntegerField()),
                ('total', models.BigIntegerField()),
=======
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.IntegerField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('phn_no', models.IntegerField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cust_id', models.IntegerField(max_length=30)),
                ('fname', models.CharField(max_length=30)),
                ('lname', models.CharField(max_length=30)),
                ('phn_no', models.IntegerField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('med_name', models.CharField(max_length=50)),
                ('qty', models.CharField(max_length=30)),
>>>>>>> 840a6ab953452f08603e5f79b0fdbb2fa9ade5bd
            ],
        ),
    ]
