# Generated by Django 5.2.5 on 2025-08-10 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma', '0020_alter_customer_phn_no_alter_employee_phn_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phn_no',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phn_no',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='phn_no',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
